using System.Text;
using System.Text.RegularExpressions;

var mode = int.Parse(args.Length > 0 ? args[0] : Query("Enter generation mode (0 = debug localization, 1 = static localization Blitz3D code): "));
var file = args.Length > 1 ? args[1] : Query("Enter the path of strings.ini: ");

switch (mode) {
    case 0:
        GenerateDebugLocalization();
        break;
    case 1:
        GenerateStaticLocalizationCode();
        break;
    default:
        Console.Error.WriteLine("Unknown mode!");
        break;
}

string Query(string queryStr) {
    Console.Error.Write(queryStr);
    return Console.ReadLine()!;
}

void GenerateDebugLocalization() {
    var sb = new StringBuilder();
    foreach (var line in File.ReadLines(file)) {
        if (line.StartsWith('[') || line.StartsWith(';') || line.StartsWith('#')) {
            Console.WriteLine(line);
            continue;
        }

        var split = line.Split('=', 2);
        if (split.Length == 1) {
            Console.WriteLine(line);
            continue;
        }
        
        split[0] = split[0].Trim();

        var any = false;
        sb.Clear();
        sb.Append(split[0]);
        for (var i = 0; split[1].Contains($"{{{i}}}"); i++) {
            if (!any) {
                any = true;
                sb.Append(" (");
            } else {
                sb.Append(", ");
            }
            sb.Append($"{{{i}}}");
        }
        if (any) {
            sb.Append(')');
        }
        
        Console.WriteLine($"{split[0]} = {sb}");
    }
}

void GenerateStaticLocalizationCode() {
    List<(string FieldName, string Group, string Key, int Count)> values = [];

    var prefix = "";

    Console.WriteLine("; THIS FILE IS AUTOMATICALLY GENERATED FROM STRINGS.INI! DO NOT EDIT IT MANUALLY!");

    var prevKey = "";
    var count = 0;
    foreach (var line in File.ReadLines(file)) {
        if (line.StartsWith('[')) {
            AddToValues(prevKey);
            prefix = line[1..^1];
            prevKey = "";
            continue;
        }
        
        if (prefix is "Item" or "Achievement" or "Achievement Desc") { continue; }
        var parts = line.Split('=', 2);
        if (parts.Length != 2) { continue; }
        
        var key = parts[0].Trim();
        var arrMatch = Patterns.Array().Match(key);
        if (arrMatch.Success) {
            key = arrMatch.Groups["Pattern"].Value;
            var val = int.Parse(arrMatch.Groups["Number"].ValueSpan);
            if (key == prevKey ? val != count + 1 : val != 1) {
                throw new("Indexed elements not in order!");
            }
        }

        if (key != prevKey) {
            AddToValues(prevKey);
            prevKey = key;
            count = 0;
        }
        count++;
    }
    AddToValues(prevKey);

    void AddToValues(string key) {
        if (key == "") { return; }
        
        values.Add((prefix.Replace(" ", "") + "_" + ToNiceKey(prevKey), prefix, key, count));
        
        string ToNiceKey(string key) {
            var keyNice = new StringBuilder();
            var upNext = true;
            foreach (var c in key) {
                var up = upNext;
                upNext = c is ' ' or '.';
                if (!upNext) {
                    if (up && keyNice.Length > 0 && char.IsDigit(keyNice[^1]) && char.IsDigit(c)) {
                        keyNice.Append('_');
                    }
                    keyNice.Append(up ? char.ToUpperInvariant(c) : c);
                }
            }
            return keyNice.ToString();
        }
    }

    Console.WriteLine();
    Console.WriteLine("Type LocalizationTable");
    foreach (var (f, g, k, c) in values) {
        if (c > 1) {
            Console.WriteLine($"    Field {f}$[{c}]");
        } else {
            Console.WriteLine($"    Field {f}$");
        }
    }
    Console.WriteLine("End Type");
    Console.WriteLine();
    Console.WriteLine(
        """
        Function LoadLocalization(loc.LocalizationTable, file$)
            Local section$
            Local f% = OpenFile(file)
            While Not Eof(f)
                Local l$ = Trim(ReadLine(f))
                If l <> "" And Instr(l, "#") <> 1 And Instr(l, ";") <> 1 Then
                    Local splitterPos = Instr(l, "=")
                    If splitterPos = 0 And Instr(l, "[") = 1 Then
                        section = Trim(Mid(l, 2, Len(l) - 2))
                    Else
                        If splitterPos = 0 Then Continue
                        Local key$ = Trim(Left(l, splitterPos - 1))
                        Local value$ = Trim(Right(l, Len(l) - splitterPos))
                        Select section
        """);
    foreach (var group in values.GroupBy(x => x.Group)) {
        Console.WriteLine($"                    Case \"{group.Key}\"");
        Console.WriteLine($"                        Select key");
        foreach (var (f, g, k, c) in group) {
            if (c > 1) {
                for (var i = 0; i < c; i++) {
                    Console.WriteLine($"                            Case \"{k}_{i+1}\" If loc\\{f}[{i+1}] = \"\" Then loc\\{f}[{i+1}] = value");
                }
            } else {
                Console.WriteLine($"                            Case \"{k}\" If loc\\{f} = \"\" Then loc\\{f} = value");
            }
        }
        Console.WriteLine($"                        End Select");
    }
    Console.WriteLine(
        """
                        End Select
                    EndIf
                EndIf
            Wend
            CloseFile(f)
        End Function
        """);
}



public static partial class Patterns {
    [GeneratedRegex(@"(?<Pattern>.*)_(?<Number>\d+)")]
    public static partial Regex Array();
}


